
const APP_DATA = {
    Category : [
        {Id:0, title: 'Mobiles', icon: "mobile-alt", clicked: false},
        {Id:1, title: 'Vehicles', icon: "car-alt", clicked: false},
        {Id:2, title: 'Property For Sale', icon: "store", clicked: false},
        {Id:3, title: 'Property For Rent', icon: "store-alt", clicked: false},
        {Id:4, title: 'Electronics & Home Aplpliances', icon: "desktop", clicked: false},
        {Id:5, title: 'Bikes', icon: "motorcycle", clicked: false},
        {Id:6, title: 'Business, Industrial & Agriculture', icon: "industry", clicked: false},
        {Id:7, title: 'Services', icon: "concierge-bell", clicked: false},
        {Id:8, title: 'Jobs', icon: "briefcase", clicked: false},
        {Id:9, title: 'Animals', icon: "paw", clicked: false},
        {Id:10, title: 'Furniture & Home Decor', icon: "couch", clicked: false},
        {Id:11, title: 'Fashion & Beauty', icon: "tshirt", clicked: false},
        {Id:12, title: 'Books, Sports & Hobbies', icon: "guitar", clicked: false},
        {Id:13, title: 'Kids', icon: "baby", clicked: false}
    ],
    SubCategory : [
        {Id:0, items:['Tablets', 'Mobile Accessories', 'Mobile Phones']},
        {Id:1, items:['Cars', 'Cars on Installment', 'Car Acessories','Spare Parts','Buses, Vans & Trucks','Rickshaw & Chingchi','Other Vehicles','Boats','Tractors & Trailers']},
        {Id:2, items:['Land & Plots','Houses','Apartments & Flats','Shops - Offices - Commercial Space','Portions & Floors']},
        {Id:3, items:['Houses','Apartments & Flats','Portions & Floors','Shops - Offices - Commercial Space','Rooms','Roommates & Paying Guests','Vacation Rentals - Guest Houses','Lands & Plots']},
        {Id:4, items:['Computers & Accessories','TV - Video - Audio','Cameras & Accessories','Games & Entertainment','Other Home Appliances','Generators, UPS & Power Solutions','Kitchen Appliances','AC & Coolers','Fridges & Freezers', 'Washing Machines & Dryers']},
        {Id:5, items:['Motorcycles','Spare Parts','Bicycles','ATV & Quads','Scooters']},
        {Id:6, items:['Business for Sale','Food & Restaurants','Trade & Industrial','Construction & Heavy Machinery','Agriculture','Other Business & Industry','Medical & Pharma']},
        {Id:7, items:['Education & Classes','Travel & Visa','Car Rental','Drivers & Taxi','Web Development','Other Services','Electronics & Computer Repair','Event Services','Health & Beauty','Maids & Domestic Help','Movers & Packers','Home & Office Repair','Catering & Restaurent','Farm & Fresh Food']},
        {Id:8, items:['Online','Marketing','Advertising & PR','Education','Customer Service','Sales','IT & Networking','Hotels & Tourism','Clerical & Advertisement','Human Resources','Accounting & Finance','Manufacturing','Medical','Domestic Staff','Part - Time','Other Jobs']},
        {Id:9, items:['Fish & Aquariums','Birds','Hens & Aseel','Cats','Dogs','Livestock','Horses','Pet Food & Accessories','Other Animals']},
        {Id:10, items:['Sofa & Chairs','Beds & Wardrobes','Home Decoration','Tables & Dining','Garden & Outdoor','Painting & Mirrors','Rugs & Carpents','Curtains & Blinds','Office Furniture','Other Household Items']},
        {Id:11, items:['Accessories','Clothes','Footwear','Jewellery','Make Up','Skin & Hair','Watches','Wedding','Lawn & Pret','Couture','Other Fashion']},
        {Id:12, items:['Books & Magazines','Musical Instruments','Sport Equipment','Gym & Fitness','Other Hobbies']},
        {Id:13, items:['Kids Furniture','Toys','Prams & Walkers','Swings & Sliders','Kids Bikes','Kids Accessories']}
    ],
    Details : [{Category: 'Mobiles', SubCategory:'Tablets', action:false, Div:[{title:'Type',type:'button', options:['Apple','Danny Tabs','Q Tabs','Samsung','Other Tablets']},{type:'button',title:'Condition', options:['No','Yes']}]},
               {Category: 'Mobiles', SubCategory:'Mobile Acessories', action:false, Div:[{title:'Type', type:'button', options:['Mobiles','Tablets']},{type:'button',title:'Condition', options:['No','Yes']}]},
               {Category: 'Mobiles', SubCategory:'Mobile Phones', action:false, Div:[{title:'Make', type:'select', options:["Acer","Alcatel","Appleasus","BlackBerry","Calme","Club","G'Five","Google","Gright","Haier","Honor","HTC","Huawei","iNew","Infinix","Lava","Lenovo","LG","Meizu","Mobilink JazzX","Motorola","Nokia","One Plus","OPPO","Panasonic","QMobile","Realme","RIVO","Samsung","Sony","Sony Ericsson","Tecno","Vivo","VOICE","Xiaomi","Zte","Other Mobiles"]},{type:'button',title:'Condition', options:['No','Yes']}]},
               {Category: 'Vehicles', SubCategory:'Cars', action:false, Div:[{title:'Make', type:'select', options:["Audi","BMW","Changan","Chevrolet","Classic & Antiques","Daewoo","Daihatsu","FAW","Honda","Hyundai","Isuzu","JAC","KIA","Land Rover","Lexus","Mazda","Mercedes","Mitsubishi","Nissan","Porsche","Proton","Prince","Range Rover","Renault","Subaru","Suzuki","Toyota","Volkswagen","United","Other Brands"]},{type:'button',title:'Condition', options:['No','Yes']},{title:'Year', type:'input'},{title:'KMs driven'}]},
               {Category: 'Vehicles', SubCategory:'Cars on Installment', action:false, Div:[{title:'Make', type:'select', options:["Audi","BMW","Changan","Chevrolet","Classic & Antiques","Daewoo","Daihatsu","FAW","Honda","Hyundai","Isuzu","JAC","KIA","Land Rover","Lexus","Mazda","Mercedes","Mitsubishi","Nissan","Porsche","Proton","Prince","Range Rover","Renault","Subaru","Suzuki","Toyota","Volkswagen","United","Other Brands"]},{type:'button',title:'Condition', options:['No','Yes']},{title:'Year', type:'input'},{title:'Transmission', type:'button', options:['Automatic','Manual']},{title:'Registered', type:'button' ,options:['Yes','No']},{title:'Down Payment (Rs)', type:'input'},{title:'Monthly Installment (Rs)', type:'input'},{title:'Installment Plan', type:'select', options:['','Flexible','1 Year','2 Years','3 Years','4 Years','5 Years','6 Years','7 Year']},{title:'Financer Type', type:'button', options:['Bank','Non Banking Company']},{title:'Transaction Type', type:'button' ,options:['Financing','Leasing']}]},
               {Category: 'Vehicles', SubCategory:'Cars Accessories', action:false ,Div:[{type:'button',title:'Condition', options:['No','Yes']}]},
               {Category: 'Vehicles', SubCategory:'Spare Parts', action:false, Div:[{type:'button',title:'Condition', options:['No','Yes']},{title:'Type', type:'button', options:['Car Parts', 'Other Parts']}]},
               {Category: 'Vehicles', SubCategory:'Buses, Vans & Trucks', action:false, Div:[{type:'button',title:'Condition', options:['No','Yes']},{title:'Year', type:'input'},{title:'KMs driven', type:'input'}]},
               {Category: 'Vehicles', SubCategory:'Rickshaw & Chingchi', action:false, Div:[{type:'button',title:'Condition', options:['No','Yes']},{title:'Year', type:'input'},{title:'KMs driven', type:'input'}]},
               {Category: 'Vehicles', SubCategory:'Other Vehicles', action:false, Div:[{type:'button',title:'Condition', options:['No','Yes']}]},
               {Category: 'Vehicles', SubCategory:'Boats', action:true},
               {Category: 'Vehicles', SubCategory:'Tractors & Trailers', action:false, Div:[{title:'Year', type:'input'},{title:'KMs driven', type:'input'}]},
               {Category: 'Property For Sale', SubCategory:'Land & Plots', action:false, Div:[{title:'Type', type:'button', options:['Agricultural Land','Commercial Plots','Files','Industrial Land','Residential Plots','Plot Form']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}]},
               {Category: 'Property For Sale', SubCategory:'Houses', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Sale', SubCategory:'Apartments & Flats', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Floor Level', type:'select', options:['','1','2','3','4','5','6','7+','Ground']}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Sale', SubCategory:'Shops - Offices - Commercial Space', action:false, Div:[{title:'Type', type:'button', options:['Office','Shop','Warehouse','Factory','Building']}, {title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}]},
               {Category: 'Property For Sale', SubCategory:'Portions & Floors', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Floor Level', type:'select', options:['','1','2','3','4','5','6','7+','Ground']}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Rent', SubCategory:'Houses', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Rent', SubCategory:'Apartments & Flats', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Floor Level', type:'select', options:['','1','2','3','4','5','6','7+','Ground']}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Rent', SubCategory:'Portions & Floors', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Floor Level', type:'select', options:['','1','2','3','4','5','6','7+','Ground']}, {title:'Furnished', type: 'button', options:['No','Yes']}]},
               {Category: 'Property For Rent', SubCategory:'Shops - Offices - Commercial Space', action:false, Div:[{title:'Type', type:'button', options:['Office','Shop','Warehouse','Factory','Building']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}, {title:'Floor Level', type:'select', options:['','1','2','3','4','5','6','7+','Ground']}]},
               {Category: 'Property For Rent', SubCategory:'Rooms', action:true},
               {Category: 'Property For Rent', SubCategory:'Roommates & Paying Guests', action:false, Div:[{title:'Furnished', type:'button', options:['No','Yes']}]},
               {Category: 'Property For Rent', SubCategory:'Vacation Rentals - Guest Houses', action:false, Div:[{title:'Bedrooms', type:'select', options:['','1','2','3','4','5', '6+', 'Studio']}, {title:'Bathrooms', type:'select', options:['','1','2','3','4','5','6','7+']}]},
               {Category: 'Property For Rent', SubCategory:'Land & Plots', action:false, Div:[{title:'Type', type:'button', options:['Agricultural Land','Commercial Plots','Files','Industrial Land','Residential Plots','Plot Form']},{title:'Area unit', type:'button', options:['Kanal','Marla','Square Feet','Square Meter','Square Yards']}, {title: 'Area', type:'input'}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Computers & Accessories', action:false, Div:[{title:'Type', type:'select', options:['Computers', 'Hard Disk', 'Internet', 'Laptops', 'Monitors', 'Printers', 'Other Accessories']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'TV - Video - Audio', action:false, Div:[{title:'Type', type:'button', options:['TV', 'Video - Audio']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Cameras & Accessories', action:false, Div:[{title:'Type', type:'button', options:['Cameras', 'Lenses', 'Other Accessories']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Games & Entertainment', action:true},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Other Home Appliances', action:false, Div:[{title:'Type', type:'select', options:['','Fans','Iron','Sewing Machines','Vacuum Cleaners','Water Dispensers','Other']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Generators, UPS & Power Solutions', action:false, Div:[{title:'Type', type:'button', options:['Batteries','Generators','Solar','UPS','Other']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Kitchen Appliances', action:false, Div:[{title:'Type', type:'select', options:['','Cooking Range','Iron','Sewing Machines','Vacuum Cleaners','Water Dispensers','Other']}]},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'AC & Coolers', action:true},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Fridges & Freezers', action:true},
               {Category: 'Electronics & Home Aplpliances', SubCategory:'Washing Machines & Dryers', action:true},
               {Category: 'Bikes', SubCategory:'Motorcycles', action:false, Div:[{title:'Make',type:'select', options:['','Crown','Eagle','Ghani','Habib','Harley Davidson','Honda','Kawasaki','Metro','Power','Ravi','Road Prince','Sohrab','Sports & Heavy Bikes','Super Power','Super Star','Suzuki','Unique','United','VESPA','Yamaha','Other Brands']},{title:'Year', type:'input'}]},
               {Category: 'Bikes', SubCategory:'Spare Parts', action:true},
               {Category: 'Bikes', SubCategory:'Bicycles', action:true},
               {Category: 'Bikes', SubCategory:'ATV & Quads', action:true},
               {Category: 'Bikes', SubCategory:'Scooters', action:false, Div:[{title:'Year',type:'input'},{title:'KMs driven', type:'input'}]},
               {Category: 'Business, Industrial & Agriculture', SubCategory:'Business for Sale', action:true},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Food & Restaurents', action:false, Div:[{title: 'Type', type:'select', options:['','Cooking Equipment','Coolers & Freezers','Crockery & Cutlery','Ovens & Ranges','Tables & Platforms','Other Restaurent Equipment']}]},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Trade & Industrial', action:false, Div:[{title: 'Type', type:'button', options:['Electrical & Electronic Equipment','Industrial Equipment','Mechanical Equipment']}]},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Construction & Heavy Machinery', action:false, Div:[{title: 'Type', type:'select', options:['','Bulldozers','Construction Material','Cranes','Dumpers','Excavators','Loaders','Rollers','Other Heavy Equipment']}]},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Agriculture', action:false, Div:[{title: 'Type', type:'button', options:['Farm Machinery & Equipment','Seeds, Crops, Pesticides & Fertilizers']}]},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Other Business & Industry', action:true},
               {Category: 'Business, Industrial & Agriculture', SubCategory: 'Medical & Pharma', action:false, Div:[{title: 'Type', type:'button', options:['Medical Equipment','Medical Supplies']}]},
               {Category: 'Services', SubCategory: 'Education & Classes', action:false, Div:[{title: 'Type', type:'button', options:['Computer','Language Classes','Music & Dance','Tutoring','Other']}]},
               {Category: 'Services', SubCategory: 'Travel & Visa', action:true},
               {Category: 'Services', SubCategory: 'Car Rental', action:true},
               {Category: 'Services', SubCategory: 'Drivers & Taxi', action:true},
               {Category: 'Services', SubCategory: 'Web Development', action:true},
               {Category: 'Services', SubCategory: 'Other Services', action:true},
               {Category: 'Services', SubCategory: 'Electronics & Computer Repair', action:false, Div:[{title: 'Type', type:'button', options:['Computer','Home Appliances','Mobile','Other Electronics']}]},
               {Category: 'Services', SubCategory: 'Event Services', action:true},
               {Category: 'Services', SubCategory: 'Health & Beauty', action:true},
               {Category: 'Services', SubCategory: 'Maids & Domestic Help', action:true},
               {Category: 'Services', SubCategory: 'Movers & Packers', action:true},
               {Category: 'Services', SubCategory: 'Home & Office Repair', action:true},
               {Category: 'Services', SubCategory: 'Catering & Restaurent', action:false, Div:[{title: 'Type', type:'button', options:['Catering','Cooked Food','Other']}]},
               {Category: 'Services', SubCategory: 'Farm & Fresh Food', action:false, Div:[{title: 'Type', type:'button', options:['Eggs','Fruits & Veh=getables','Milk','Other']}]},
               {Category: 'Jobs', SubCategory: 'Online', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Marketing', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Advertising & PR', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Education', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Customer Service', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Sales', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'IT & Networking', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Hotels & Tourism', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Clerical & Administration', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Human Resources', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Accounting & Finance', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Manufacturing', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Medical', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Domestic Staff', action:false, Div:[{title:'Type', type:'input', options:['','Baby Sitter','Cook','Driver','Gardener','Maid','Patient Attendant','Security Guard','Other']},{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Part - Time', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Jobs', SubCategory: 'Other Jobs', action:false, Div:[{title: 'Ad Type', type:'button', options:['CVs & Resumes','Job offer']},{title:'Position type', type:'button', options:['Contract','Full-time','Part- time','Temporary']}, {title:'Salary period', type:'button', options:['Hourly','Monthly','Weekly','Yearly']},{title:'Salary from',type:'input'},{title:'Salary to',type:'input'}]},
               {Category: 'Animals', SubCategory: 'Fish & Aquariums', action:true},
               {Category: 'Animals', SubCategory: 'Birds', action:true},
               {Category: 'Animals', SubCategory: 'Hens & Aseel', action:true},
               {Category: 'Animals', SubCategory: 'Cats', action:true},
               {Category: 'Animals', SubCategory: 'Dogs', action:false, Div:[{title: 'Type', type:'select', options:['','Beagle','Boxer','Bulldog','Cocker Spaniel','Dalmatian','Doberman','German Shepherd','Golden Retriever','Labrador','Pomeranian','Pug','Rottweiler','Russian Dogs','Other Breeds']}]},
               {Category: 'Animals', SubCategory: 'Livestock', action:false, Div:[{title: 'Type', type:'select', options:['','Buffaloes','Bulls','Cows','Goats','Sheep','Other Livestock']}]},
               {Category: 'Animals', SubCategory: 'Horses', action:true},
               {Category: 'Animals', SubCategory: 'Pet Foods & Accessories', action:true},
               {Category: 'Animals', SubCategory: 'Other Animals', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Sofa & Chairs', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Beds & Wardrobes', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Home Decoration', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Tables & Dining', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Garden & Outdoor', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Painting & Mirrors', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Rugs & Carpets', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Curtains & Blinds', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Office Furniture', action:true},
               {Category: 'Furniture & Home Decor', SubCategory: 'Other Household Items', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Accessories', action:false, Div:[{title:'Type', type:'button', options:['Accessories for Men','Accessories for Women']}]},
               {Category: 'Fashion & Beauty', SubCategory: 'Clothes', action:false, Div:[{title:'Type', type:'button', options:['Clothes for Men','Clothes for Women']}]},
               {Category: 'Fashion & Beauty', SubCategory: 'Footwear', action:false, Div:[{title:'Type', type:'button', options:['Footwear for Men','Footwear for Women']}]},
               {Category: 'Fashion & Beauty', SubCategory: 'Jewellery', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Make Up', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Skin & Hair', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Watches', action:false, Div:[{title:'Type', type:'button', options:['Watches for Men','Watches for Women']}]},
               {Category: 'Fashion & Beauty', SubCategory: 'Wedding', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Lawn & Pret', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Couture', action:true},
               {Category: 'Fashion & Beauty', SubCategory: 'Other Fashion', action:true},
               {Category: 'Books, Sports & Hobbies', SubCategory: 'Books & Magazines', action:false, Div:[{title:'Type', type:'button', options:['Education & Training','Literature & Fiction','Professional','Other Books']}]},
               {Category: 'Books, Sports & Hobbies', SubCategory: 'Musical Instrument', action:true},
               {Category: 'Books, Sports & Hobbies', SubCategory: 'Sports Equipment', action:true},
               {Category: 'Books, Sports & Hobbies', SubCategory: 'Gym & Fitness', action:true},
               {Category: 'Books, Sports & Hobbies', SubCategory: 'Other Hobbies', action:true},
               {Category: 'Kids', SubCategory: 'Kids Furniture', action:true},
               {Category: 'Kids', SubCategory: 'Toys', action:true},
               {Category: 'Kids', SubCategory: 'Prams & Walkers', action:true},
               {Category: 'Kids', SubCategory: 'Swings & Slides', action:true},
               {Category: 'Kids', SubCategory: 'Kids Bikes', action:true},
               {Category: 'Kids', SubCategory: 'Kids Accessories', action:true}
               

    ],
    ads:[],
    Locations:['Punjab','Islamabad Capital Territory','Sindh','Khyber Pakhtunkhwa','Azad Kashmir','Balochistan','Northeren Areas']
}

export default (state = APP_DATA, action) => {
    console.log('action ==>',action)
    switch (action.type) {
        case "SETDATA":
            return ({
                ...state,
                users: [...state.users,action.payload]
            })
        case "SETAD":
            return ({
                ...state,
                users: [...state.ads,action.payload]
            })
    }
    return state;
}